### PR TITLE
Change collector to support deep nested relations

### PR DESCRIPTION
**Pull request by Fryguy**
@agrare Please review.

### CODE REVIEW

**Comment by Fryguy** [comment]
I need to add more tests to handle the various nested relations, e.g. has_many, has_one, etc.  I also would like to test double nested has_many, such as disks -> partitions -> volumes.

**Comment by agrare** [comment]
Nice no N+1 :+1:

**Comment by Fryguy** [comment]
@agrare Let's get this merged, and I'll do a follow up with the tests.

**Comment by agrare** [comment]
:+1: sounds good @Fryguy

**Pull request merged**
