### PR TITLE
More UI changes

### PR DESCRIPTION
**Pull request by PanSpagetka**
### TODO
1. [x] Change Label from Platform Synchronization to Global Synchronization 
2. [x] Add Red Hat logo to menu 
3. [x] Add real info texts

#### New screens
Screenshot from 2019-07-09 10-06-52
Screenshot from 2019-07-09 10-07-27
#### Menu icon
Screenshot from 2019-07-16 16-37-11

### CODE REVIEW

**Comment by PanSpagetka** [comment]
I have got in contact with @inoxx03 and we figure out some info texts. Please check if it is ok.

@Loicavenel @h-kataria @martinpovolny @Fryguy

**Comment by Loicavenel** [comment]
ACK for me

**Comment by h-kataria** [comment]
looks good

**Comment by PanSpagetka** [comment]
@terezanovotna according to Red Hat guidelines Red Hat's hat must be red. Is it ok to have red hat as an icon? Because Red Hat's red hat is red and other icons are grey, that means they are not red as Red Hat's hat. :trollface:

**Comment by h-kataria** [comment]
@terezanovotna does this look to be merged or you have suggestions for the icon?

**Comment by terezanovotna** [comment]
Robin, you are right - the icon should be red according to standards. 

On the other hand, this is a taking us outside of CF to a different product and having it red would bring too much attention. Let's keep it consistent with the rest of the icons and have it grey.

**Comment by PanSpagetka** [comment]
@terezanovotna Menu icon is now grey, same as the others. Screenshots updated.

**Comment by terezanovotna** [comment]
This looks great! thanks for making all the changes

**Pull request merged**
